### ISSUE TITLE
Implement Raster Functionality

### ISSUE THREAD

**Issue by thewanderer41** [PlusOneData/NetworkInfection#3]
The SpaDES package will use a Raster image to simulate people moving through the office space.  However, we need functions written which will actually extract or calculate information from the image.  How do we represent walls? Desks? Paths?

@benjaminortizulloa I could use a hand here.  In [this code](https://github.com/PredictiveEcology/SpaDES-modules/blob/master/modules/caribouMovementLcc/caribouMovementLcc.R), I have no idea how line 185 works.

**Comment by collinschwantes** [comment]
Too complicated, closing for now
