### ISSUE TITLE
Connect infection.graph with SpaDES

### ISSUE THREAD

**Issue by thewanderer41** [PlusOneData/NetworkInfection#5]
It looks like Spades is set to run from beginning to end while executing events at certain intervals.  We originally expected Spades to spit out connectivity graphs at certain intervals.  However, we also want infection.graph to simulate agents being removed from the population through quarantining.  That means Spades would have to wait for infection.graph to determine which individuals are removed and then continue computing new connectivity networks.  This interdependence means that Spades will likely have to intermittently call infection.graph to update active agents in the simulation.

**Comment by collinschwantes** [comment]
This is too complicated and may be revisited at a later date
